### ISSUE TITLE
header sign貌似变了，其他接口无法破解

### ISSUE THREAD

**Issue by lonycc** [lk-li/spider_reverse#1]
如题，试了下其他接口，比如https://www.qcc.com/api/datalist/newslist?keyNo=h7a5a6c405fca1754b9ef13a6a174600&showMapTag=true&stockCode=09988.HK，返回 {'status': 435, 'message': '未知错误'}

**Comment by chenyucheng0503** [comment]
请问你破解sign了吗

**Comment by lonycc** [comment]
> 

已破解，http://42.194.197.96/openapis
